development:
  secret_key_base: makingdevs
  mailer_host: <%= ENV["VARIABLE_HOST"] %>
  mailer_port: <%= ENV["VARIABLE_PORT"] %>
  mailer_user: <%= ENV["VARIABLE_USERNAME"] %>
  mailer_passwrod: <%= ENV["VARIABLE_PASSWORD"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_bucket_name: <%= ENV["AWS_BUCKET_NAME"] %>
  aws_bucket_region: <%= ENV["AWS_BUCKET_REGION"] %>

environment:
  secret_key_base: supersecretkeybase

production:
  secret_key_base: makingdevs
  mailer_host: <%= ENV["VARIABLE_HOST"] %>
  mailer_port: <%= ENV["VARIABLE_PORT"] %>
  mailer_user: <%= ENV["VARIABLE_USERNAME"] %>
  mailer_passwrod: <%= ENV["VARIABLE_PASSWORD"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_bucket_name: <%= ENV["AWS_BUCKET_NAME"] %>
  aws_bucket_region: <%= ENV["AWS_BUCKET_REGION"] %>
  bonsai_url: <%= ENV["BONSAI_URL"] %>
